export const FETCH_PRESENTATION_START = 'FETCH_PRESENTATION_START';
export const FETCH_PRESENTATION_SUCCESS = 'FETCH_PRESENTATION_SUCCESS';
export const FETCH_PRESENTATION_FAIL = 'FETCH_PRESENTATION_FAIL';

export const POST_PRESENTATION_START = 'POST_PRESENTATION_START';
export const POST_PRESENTATION_SUCCESS = 'POST_PRESENTATION_SUCCESS';
export const POST_PRESENTATION_FAIL = 'POST_PRESENTATION_FAIL';
